Repository appuio/component-openshift4-service-mesh, pull requests merged in 2023-03, with the labels that each got.

#1 Initial implementation
  .editorconfig
  .github/workflows/component-test.yaml
  .github/workflows/test.yaml
  .gitignore
  Makefile
  Makefile.vars.mk
  class/defaults.yml
  component/.cruft.json
  component/.github/workflows/test.yaml
  component/.yamllint.yml
  component/Makefile
  component/Makefile.vars.mk
  component/class/defaults.yml
  component/class/openshift4-service-mesh.yml
  component/component/app.jsonnet
  component/component/main.jsonnet
  component/main.jsonnet
  component/tests/defaults.yml
  component/tests/golden/defaults/openshift4-service-mesh/apps/openshift4-service-mesh.yaml
  component/tests/golden/defaults/openshift4-service-mesh/openshift4-service-mesh/es_operator.yaml
  component/tests/golden/defaults/openshift4-service-mesh/openshift4-service-mesh/namespace.yaml
  component/tests/golden/defaults/openshift4-service-mesh/openshift4-service-mesh/operator.yaml
  docs/modules/ROOT/pages/references/parameters.adoc
  renovate.json
  tests/defaults.yml
Labels: enhancement

#2 Add configuration package
  .github/workflows/package-test.yaml
  README.md
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/references/package_classes.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/partials/nav.adoc
  package/.cruft.json
  package/.github/workflows/test.yaml
  package/.gitignore
  package/.yamllint.yml
  package/Makefile
  package/Makefile.vars.mk
  package/main.yml
  package/preview.yml
  package/tests/defaults.yml
  package/tests/golden/defaults/openshift-operators-redhat/apps/openshift4-operators.yaml
  package/tests/golden/defaults/openshift-operators-redhat/openshift4-operators/openshift-operators-redhat.yaml
  package/tests/golden/defaults/openshift4-service-mesh/apps/openshift4-service-mesh.yaml
  package/tests/golden/defaults/openshift4-service-mesh/openshift4-service-mesh/es_operator.yaml
  package/tests/golden/defaults/openshift4-service-mesh/openshift4-service-mesh/namespace.yaml
  package/tests/golden/defaults/openshift4-service-mesh/openshift4-service-mesh/operator.yaml
  package/tests/golden/defaults/syn-openshift-distributed-tracing/apps/openshift4-operators.yaml
  package/tests/golden/defaults/syn-openshift-distributed-tracing/openshift4-operators/syn-openshift-distributed-tracing.yaml
  package/tests/golden/defaults/syn-openshift-kiali/apps/openshift4-operators.yaml
  package/tests/golden/defaults/syn-openshift-kiali/openshift4-operators/syn-openshift-kiali.yaml
Labels: enhancement

#4 Fix component config parameter in package class
  package/main.yml
  package/tests/defaults.yml
  package/tests/golden/defaults/openshift4-service-mesh/openshift4-service-mesh/operator.yaml
Labels: bug

#6 Add Aldebaran Tech as CodeOwners
  CODEOWNERS
Labels: documentation
